# publisher: Juergen Smolka 
# info-page: http://OnlineTeaTimer.blogspot.com/
# contact:   http://smolka.lima-city.de/contact.php
name: ttimer
version: "0.0.2-xxxx"
summary: Timer for systems w/ and w/o java
description: tea-timer for systems w/ or w/o java --- if java and javaws are installed already, you might prefer the lean version which you can download and install via http://onlineteatimer.blogspot.com/
grade: stable         # must be 'stable' to release into candidate/stable channels
confinement: strict   # use 'strict' once you have the right plugs and slots
icon: bin/icon.png

apps:
  ttimer:
    command: bin/ttimer
    desktop: bin/ttimer.desktop
    plugs: [home, network, pulseaudio, unity7, x11]    

parts:
  java-jre:
    plugin: jdk
    source: .
  app-wrapper:
    plugin: dump
    source: .
